export const serviceSliderData = [
    {
        param: "enterprise-resource-planning",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "cloud-infrastructure",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "eCommerce-solutions",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "learning-management-system",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "customer-relation-management",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "project-management",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "business-intelligence-solutions",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "human-resource-management",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "web-development",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "mobile-app-development",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "testing",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "application-development",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "UI-UX-design",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "infrastructure-services",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "managed-IT-services",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "IT-sourcing",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "IT-consulting",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "IT-support",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "data-analytics",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "cloud-cybersecurity",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "IT-staff-augmentation",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "dedicated-development-team",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
    {
        param: "technical-staff-outsourcing",
        heading: `Case Studies`,
        items: [
            {
                id: 1,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 2,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 3,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 4,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 5,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 6,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 7,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 8,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 9,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
            {
                id: 10,
                imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
                text1: 'Important',
                text2: 'Brian Adams',
                description: "Lorem ipsum dolor sit amet adipiscing.",
                btnText: "Read More",
            },
        ],
    },
]