export const QATestingData ={
    heading: <><span style={{color:" #32D460"}}> QA and Software Testing</span> Services We Provide</>, 
    description:<>Reduced overhead. Faster product release cycles. Access to specialized experts and tools. These are all benefits of outsourcing your QA and software testing to our top 1% engineers. Whether you need a few QA engineers or an entire automation team, our flexible engagement models to ensure a seamless partnership.</> ,
    detail: [
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Azure and AWS Consulting Services",para:["Cutting-edge design techniques","Intuitive and interactive UI/UX","12+ team members of UI/UX experts."]},
       {title: "Hire Developers Within 72 Working Hours and Save Upto 30% At Your Total Costs!"},
        
       
    ],
    detail1: [
        {title: "Azure and AWS Consulting Services",para:["With our load and endurance tests, we simulate  “rush hour” scenarios to identify performance  bottlenecks. This means that when you get a  traffic surge, your application remains swift and  responsive. Stress testing pushes your software  beyond its limits, revealing its breaking points."," Using popular tools such as JMeter, LoadRunner, and Gatling, we simulate thousands of concurrent users. We monitor response times, throughput rates, and system stability. Performance testing keeps your software responsive and resilient even during peak demand."]},
        {title: "Azure and AWS Consulting Services",para:["With our load and endurance tests, we simulate  “rush hour” scenarios to identify performance  bottlenecks. This means that when you get a  traffic surge, your application remains swift and  responsive. Stress testing pushes your software  beyond its limits, revealing its breaking points."," Using popular tools such as JMeter, LoadRunner, and Gatling, we simulate thousands of concurrent users. We monitor response times, throughput rates, and system stability. Performance testing keeps your software responsive and resilient even during peak demand."]},
        {title: "Azure and AWS Consulting Services",para:["With our load and endurance tests, we simulate  “rush hour” scenarios to identify performance  bottlenecks. This means that when you get a  traffic surge, your application remains swift and  responsive. Stress testing pushes your software  beyond its limits, revealing its breaking points."," Using popular tools such as JMeter, LoadRunner, and Gatling, we simulate thousands of concurrent users. We monitor response times, throughput rates, and system stability. Performance testing keeps your software responsive and resilient even during peak demand."]},
        {title: "Azure and AWS Consulting Services",para:["With our load and endurance tests, we simulate  “rush hour” scenarios to identify performance  bottlenecks. This means that when you get a  traffic surge, your application remains swift and  responsive. Stress testing pushes your software  beyond its limits, revealing its breaking points."," Using popular tools such as JMeter, LoadRunner, and Gatling, we simulate thousands of concurrent users. We monitor response times, throughput rates, and system stability. Performance testing keeps your software responsive and resilient even during peak demand."]},
        {title: "Azure and AWS Consulting Services",para:["With our load and endurance tests, we simulate  “rush hour” scenarios to identify performance  bottlenecks. This means that when you get a  traffic surge, your application remains swift and  responsive. Stress testing pushes your software  beyond its limits, revealing its breaking points."," Using popular tools such as JMeter, LoadRunner, and Gatling, we simulate thousands of concurrent users. We monitor response times, throughput rates, and system stability. Performance testing keeps your software responsive and resilient even during peak demand."]},
        {title: "Azure and AWS Consulting Services",para:["With our load and endurance tests, we simulate  “rush hour” scenarios to identify performance  bottlenecks. This means that when you get a  traffic surge, your application remains swift and  responsive. Stress testing pushes your software  beyond its limits, revealing its breaking points."," Using popular tools such as JMeter, LoadRunner, and Gatling, we simulate thousands of concurrent users. We monitor response times, throughput rates, and system stability. Performance testing keeps your software responsive and resilient even during peak demand."]},
     ],}
      

