export const industriesWeWorkWithData = [
    {
        param: "enterprise-resource-planning",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "cloud-infrastructure",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "eCommerce-solutions",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "learning-management-system",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "customer-relation-management",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "project-management",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "business-intelligence-solutions",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "human-resource-management",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "web-development",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "mobile-app-development",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "testing",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "application-development",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "UI-UX-design",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "infrastructure-services",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "managed-IT-services",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "IT-sourcing",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "IT-consulting",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "IT-support",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "data-analytics",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "cloud-cybersecurity",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "IT-staff-augmentation",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "technical-staff-outsourcing",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
    {
        param: "technical-staff-outsourcing",
        heading: "Industries we worked with",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        detail: [
            "Health Care",
            "Construction",
            "E Commerce and Retails",
            "Oil And Gas",
            "Logistic And Transportation",
            "Banking",
            "Insurance",
            "Finance",
            "Telecommunication",
        ],
    },
]