export const SolutionProvideData = [
  {
    param: "construction",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "insurance",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "banking",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "telecommunication",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "retail-ecommerce",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "finance",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "oil-gas",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "logistics-transportation",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
  {
    param: "healthcare",
    title: "Solutions We Provide",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..`,
    cardData: [
      {
        labelName: "Banking Solutions for All Major Segments",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgblue.webp?alt=media&token=870a00a1-4f14-471c-88b1-e54faf427c22",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Fsettingbgwhite.webp?alt=media&token=e04009ea-1fd9-4f3c-beb7-c531a351c326",
        discription: `Banking solutions we offer allow to build the planning and reporting system for effective financial management and bank risk control, improves customer relationship service, automate operations and complex banking transactions..`,
        detail: [
          "Retail Banking",
          "Business Banking",
          "Corporate Banking",
          "Wealth Management",
          "Credit Unions",
          "Treasury",
          "Financial Risk Management",
        ],
      },
      {
        labelName: "Digital Banking for Every Major Provider",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgblue.webp?alt=media&token=da6b4749-a8c6-451c-88d9-10276e394aad",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Funionbgwhite.webp?alt=media&token=ba877fe0-9659-48ca-a926-1b4044b1f0dd",
        discription: `We provide digital banking solutions to all major financial providers:.`,
        detail: [
          "Banks",
          "Investors",
          "Insurers",
          "Credit unions",
          "Brokers",
          "Lenders",
        ],
      },
      {
        labelName: "Banking Software Solutions",
        logo: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgblue.webp?alt=media&token=703796f8-55ab-426d-bef6-430b39e5bd90",
        logohover: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/hiring%2Flaptopbgwhite.webp?alt=media&token=ebcc6b86-dd1b-4734-b38a-a24377dbdc86",
        discription: `We develop and implement, internet banking, mobile banking, customer portal, CRM, loyalty program and more. See below:.`,
        detail: [
          "Core Banking System",
          "Customized Banking Software",
          " Banking Process Automation",
          "Component Integrations",
          " KYC and AML",
          " Cloud Banking",
          " ATM & Self-Service Banking",
          "ERP and Payment Processing",
          " Artificial Intelligence",
          "  Mobile Banking",
          " Robotic Processing Automation",
          "Data Warehouse",
        ],
      },
    ],
  },
]
