export const BankingBannerData = [
    {
        param: "construction",
        text1: 'construction',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "insurance",
        text1: 'insurance',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "banking",
        text1: 'banking',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "telecommunication",
        text1: 'telecommunication',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "retail-ecommerce",
        text1: 'retail ecommerce',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "finance",
        text1: 'finance',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "oil-gas",
        text1: 'oil gas',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "logistics-transportation",
        text1: 'logistics transportation',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
    {
        param: "healthcare",
        text1: 'healthcare',
        text2: 'Development',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
        image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/backing%2FBanking.webp?alt=media&token=aaf343cb-4f48-4952-900b-a23fa19d7ae7",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy. ",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    },
]
