export const HiringTimeData = [
  {
    param: "react",
    title: "Fast Track Your Team: Hire Top Developers in 48 Hours.",
    description: `Don't let talent shortages slow you down. Fill your tech gaps with our exceptional talent.`,
    bodyText: `Stay ahead with CodersWire's agile solutions. Don't let talent shortages impede your growth. Hire top developers in 48 hours to fast-track your team and maintain peak efficiency effortlessly.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
    
  },
  {
    param: "PHP",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "c%2B%2B",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "node.Js",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "Python",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "java",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "node",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: ".NET",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "HTML",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "CSS",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "meteor",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "ember",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "RR",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "react-native",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "front-end",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "back-end",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "flask",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "laravel",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "angular",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "go-lang",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "vue.js",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "redux",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
  {
    param: "javascript",
    title: "Hire Developers within 48 Hours",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    CardTitle1: "$3500",
    CardTitle2: "Monthly (USD)",
    CardDescription: `4+ Years of Expert Senior DevOps Developers 160 hours`,
  },
]
