export const dotNetBanner = [
    {
        param : "react",
        text1: 'Hire ',
        text2: 'React Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "PHP",
        text1: 'Hire ',
        text2: 'PHP Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "c%2B%2B",
        text1: 'Hire ',
        text2: 'C++ Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "node.Js",
        text1: 'Hire ',
        text2: 'node.Js Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "Python",
        text1: 'Hire ',
        text2: 'Python Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "java",
        text1: 'Hire ',
        text2: 'java Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "node",
        text1: 'Hire ',
        text2: 'node Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : ".NET",
        text1: 'Hire ',
        text2: '.NET Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "HTML",
        text1: 'Hire ',
        text2: 'HTML Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "CSS",
        text1: 'Hire ',
        text2: 'CSS Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "meteor",
        text1: 'Hire ',
        text2: 'meteor Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "ember",
        text1: 'Hire ',
        text2: 'ember Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "RR",
        text1: 'Hire ',
        text2: 'RR Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "react-native",
        text1: 'Hire ',
        text2: 'react native Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "front-end",
        text1: 'Hire ',
        text2: 'front end Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "back-end",
        text1: 'Hire ',
        text2: 'back-end Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "flask",
        text1: 'Hire ',
        text2: 'flask Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "laravel",
        text1: 'Hire ',
        text2: 'laravel Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "angular",
        text1: 'Hire ',
        text2: 'angular Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "go-lang",
        text1: 'Hire ',
        text2: 'go lang Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "vue.js",
        text1: 'Hire ',
        text2: 'vue.js Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "redux",
        text1: 'Hire ',
        text2: 'redux Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
    {
        param : "javascript",
        text1: 'Hire ',
        text2: 'javascript Developers',
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.`,
        image : "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
        // form data
        heaidng: "Share What’s in your ",
        mind: "mind",
        detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
        detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
    },
   
] 
