export const WeAreExcitedData = [
    {
        param: "construction",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "insurance",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "banking",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "telecommunication",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "retail-ecommerce",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "finance",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "oil-gas",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "logistics-transportation",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        param: "healthcare",
        heading : "Excited To Discuss",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your Banking software development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
]