export const HomeTeamData ={
  id: "Team Data",
  title: `Developers designers project managers and product managers we in our talent network`,
  cardData: [
    {
      labelName: "Developers",
      labelHeading: "Developers",
      detail: [
        {
          Name: "Michel Rechard",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Firady",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Jackson",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Rechard",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Firady",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2Fhometeam2.webp?alt=media&token=827be9ad-8a06-400e-9071-38bcfdb1c830",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Jackson",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          experienceTime: "7+ Year Experience in this Field",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
      ],
    },
    {
      labelName: "Designers",
      labelHeading: "Designers",
      detail: [
        {
          Name: "Rockey Handsome",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Rockey Bhai",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2Fhometeam2.webp?alt=media&token=827be9ad-8a06-400e-9071-38bcfdb1c830",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Rockey Man",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Rockey Handsome",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Rockey Bhai",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2Fhometeam2.webp?alt=media&token=827be9ad-8a06-400e-9071-38bcfdb1c830",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Rockey Man",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
      ],
    },
    {
      labelName: "Projects Managers",
      labelHeading: "Projects Managers",
      detail: [
        {
          Name: "Michel Rechard",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Firady",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2Fhometeam2.webp?alt=media&token=827be9ad-8a06-400e-9071-38bcfdb1c830",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Handsome",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Rechard",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Firady",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2Fhometeam2.webp?alt=media&token=827be9ad-8a06-400e-9071-38bcfdb1c830",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Michel Handsome",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          experienceTime: "7+ Year Experience in this Field",
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
      ],
    },
    {
      labelName: "Products Managers",
      labelHeading: "Product Managers",
      detail: [
        {
          Name: "Mr Beast",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Mr Bean",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2Fhometeam2.webp?alt=media&token=827be9ad-8a06-400e-9071-38bcfdb1c830",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Mr Vickey",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Mr Beast",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam1.webp?alt=media&token=7a96553f-48c3-43f3-8d54-52de6807e545",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Mr Bean",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2Fhometeam2.webp?alt=media&token=827be9ad-8a06-400e-9071-38bcfdb1c830",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
        {
          Name: "Mr Vickey",
          imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/HomeTeam%2FHometeam3.webp?alt=media&token=fbce3737-fe3c-484e-b9b7-cd97078b4b16",
          Verification: <><strong>Verified Expert</strong> in Project Management </>,
          skill: "EXPERTISE",
          chip: ["JAVA", "SQL", "PYTHON", "AGILE"],
        },
      ],
    },
  ]
}
