export const softwareServicesBannerData = [
  {
    param: "enterprise-resource-planning",
    text1: "enterprise resource planning",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "cloud-infrastructure",
    text1: "cloud infrastructure",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "eCommerce-solutions",
    text1: "E-commerce solutions",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "learning-management-system",
    text1: "Learning Management System",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "customer-relation-management",
    text1: "customer relation management",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "project-management",
    text1: "project management",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "business-intelligence-solutions",
    text1: "business intelligence solutions",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "human-resource-management",
    text1: "human resource management",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "web-development",
    text1: "web development",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "mobile-app-development",
    text1: "mobile app development",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "testing",
    text1: "testing",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "application-development",
    text1: "application development",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "UI-UX-design",
    text1: "UI / UX design",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "infrastructure-services",
    text1: "infrastructure services",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "managed-IT-services",
    text1: "managed IT services",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "IT-sourcing",
    text1: "IT sourcing",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "IT-consulting",
    text1: "IT consulting",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "IT-support",
    text1: "IT support",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "data-analytics",
    text1: "data analytics",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "cloud-cybersecurity",
    text1: "cloud cybersecurity",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "IT-staff-augmentation",
    text1: "IT staff augmentation",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "dedicated-development-team",
    text1: "dedicated development team",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  {
    param: "technical-staff-outsourcing",
    text1: "technical staff outsourcing",
    text2: "Services",
    image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    heaidng: "Share What’s in your ",
    mind: "mind",
    detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
    detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  },
  // {
  //   param: "cloud-infrastructure",
  //   text1: "cloud infrastructure",
  //   text2: "Services",
  //   image: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2Fservices.webp?alt=media&token=8546c23d-ff30-4c8d-b48b-61a20f3dcb13",
  //   description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
  //   heaidng: "Share What’s in your ",
  //   mind: "mind",
  //   detailTop: "Fill the form to avail our services, we will get back to you in a couple of hours.",
  //   detailbuttom: "By submitting this form, you agree to our Terms of use and Privacy policy.",
  // },
]