export const contactData = [
    {
        id : "enterprise resource planning",
        param: "enterprise-resource-planning",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your enterprise resource planning needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "cloud infrastructure",
        param: "cloud-infrastructure",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your cloud infrastructure needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "E-Commerce solutions",
        param: "eCommerce-solutions",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your eCommerce solutions needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "learning management system",
        param: "learning-management-system",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your learning management system needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "customer relation management",
        param: "customer-relation-management",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your customer relation management needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "project management",
        param: "project-management",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your project management needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "business intelligence solutions",
        param: "business-intelligence-solutions",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your business intelligence solutions needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "human resource management",
        param: "human-resource-management",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your human resource management needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "web development",
        param: "web-development",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your web development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "mobile app development",
        param: "mobile-app-development",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your mobile app development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "testing",
        param: "testing",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your testing needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "application development",
        param: "application-development",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your application development needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "UI/UX design",
        param: "UI-UX-design",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your UI/UX design needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "infrastructure services",
        param: "infrastructure-services",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your infrastructure services needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "managed IT services",
        param: "managed-IT-services",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your managed IT services needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "IT sourcing",
        param: "IT-sourcing",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your IT sourcing needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "IT consulting",
        param: "IT-consulting",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your IT consulting needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "IT support",
        param: "IT-support",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your IT support needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "data analytics",
        param: "data-analytics",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your data analytics needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "cloud cybersecurity",
        param: "cloud-cybersecurity",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your cloud cybersecurity needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "IT staff augmentation",
        param: "IT-staff-augmentation",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your IT staff augmentation needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "dedicated development team",
        param: "dedicated-development-team",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your dedicated development team needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
        id : "technical staff outsourcing",
        param: "technical-staff-outsourcing",
        image: 'https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/services%2FDesigner%20and%20programmer.webp?alt=media&token=585952b2-b7e0-4d62-b75c-d423cde79e2b',
        title: 'We are excited to discuss your technical staff outsourcing needs!',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
]