export const homeSliderData = {
    id : "HomeSlider",
    heading: `Business Insights and Case Studies.`,
    items: [
        {
            id: 1,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider1.webp?alt=media&token=28ab7f4a-a9dc-4db5-926b-3054dfea89f8",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 2,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider2.webp?alt=media&token=33d815c9-211e-4253-8808-7f0f3bfe52d5",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 3,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Slider3.webp?alt=media&token=a7097dc8-f7f4-4d59-8065-a0492b949f63",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 4,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Solution.webp?alt=media&token=c925c403-8dfb-4ea4-9827-f0850233f0d0",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 5,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Solution.webp?alt=media&token=c925c403-8dfb-4ea4-9827-f0850233f0d0",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 6,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Solution.webp?alt=media&token=c925c403-8dfb-4ea4-9827-f0850233f0d0",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 7,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Solution.webp?alt=media&token=c925c403-8dfb-4ea4-9827-f0850233f0d0",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 8,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Solution.webp?alt=media&token=c925c403-8dfb-4ea4-9827-f0850233f0d0",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 9,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Solution.webp?alt=media&token=c925c403-8dfb-4ea4-9827-f0850233f0d0",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
        {
            id: 10,
            imageSrc: "https://firebasestorage.googleapis.com/v0/b/coders-wire.appspot.com/o/Solution.webp?alt=media&token=c925c403-8dfb-4ea4-9827-f0850233f0d0",
            text1: 'Important',
            text2: 'Brian Adams',
            description: "Lorem ipsum dolor sit amet adipiscing.",
            btnText: "Read More",
        },
    ],
}